### ISSUE TITLE
prerequisite of GIS packages for the hex2GML

### ISSUE THREAD

**Issue by MJGibson** [ldesousa/hex-utils#9]
error:
Leaded input HASC, converting...
Traceback (most recent call last):
  File "C:\Prog\GITS\hex-utils\hex_utils\hasc.py", line 88, in saveAsGML
    from osgeo import ogr
ImportError: No module named 'osgeo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Prog\GITS\hex-utils\hex_utils\hasc2gml.py", line 52, in <module>
    main()
  File "C:\Prog\GITS\hex-utils\hex_utils\hasc2gml.py", line 49, in main
    hexGrid.saveAsGML(outputFile)
  File "C:\Prog\GITS\hex-utils\hex_utils\hasc.py", line 92, in saveAsGML
    apt install python-gdal""")
## TypeError: exceptions must derive from BaseException

Obviously I need the osgeo packages, which I can surmise are 'geo' related, i.e. GIS packages.

Should note the prerequisite for software in the readme ^_^

**Comment by ldesousa** [comment]
ToDo:
1. Check if the import is successful and issue an error if GDAL is missing.
2. Create a requirements.txt file (to be used with pip).
3. Reference GDAL in install instructions (README file).
